### ISSUE TITLE
CARMAWebUI for testarossa release doesn't show version

### ISSUE THREAD

**Issue by aswath1** [usdot-fhwa-stol/CARMAPlatform#473]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
CARMAWebUI for testarossa release doesn't show version testarossa on the Web UI

### Expected behavior
The web ui should show the version as testarossa.

### Software version this applies to

testarossa 

### Actual behavior
The web ui doesn't show the version as testarossa.

### Steps to reproduce the behavior
1. start the carma platform
2. open the web ui and check the version located on the footer. 

### Related work
Link to related tickets or prior related work here.
https://github.com/usdot-fhwa-stol/CARMAPlatform/issues/342

**Comment by maefromm** [comment]
This issue only occured in the Blue Lexus and Pacifica. Ford Fusion worked. 

The issue was caused due to the docker group id in the vehicle host PC and web-ui image is using different IDs, which didn't allow it to execute the docker inspect command. Eventhough we already have the docker:www-data in the etc/groups in both the image and the host PC, it was not enough.  The group # is 999  in the image and 998 on the PC. Switching the group id is a more work and can be complicated. 

At the meantime, the work around is to issue this command "sudo chmod 777 /var/run/docker.sock" on the vehicle PC, which allows everyone to access the docker.sock file. 

More information explained in http://blog.gaiterjones.com/docker-in-docker-permissions/

Screenshots below: 
![BlueLexus_WebUIImage_Group](https://user-images.githubusercontent.com/27976519/71206523-bb2b1380-2272-11ea-9d99-ee6ed3109e44.png)
![BlueLexus_VehiclePC_Group](https://user-images.githubusercontent.com/27976519/71206524-bbc3aa00-2272-11ea-8034-a11838cc8052.png)

**Comment by maefromm** [comment]
Created a startup script that will need to be manually installed if the group id does not match with the container's docker group id=999. Will check in under engineering tools.

**Comment by aswath1** [comment]
The issue is fixed through PR : release/testarossa - component fix for trajectory error and ensuring docker id is 999 #480
